version: '3'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - agentic-network

  app:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    networks:
      - agentic-network

  chainlit:
    build: 
      context: .
      dockerfile: Dockerfile-chainlit
    ports:
      - "8000:8000"
    depends_on:
      - app
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    networks:
      - agentic-network

networks:
  agentic-network:
    driver: bridge
